version: 2

models:
  - name: dim_hosts_cleansed
    description: Cleansed table for Airbnb hosts
    columns:
      - name: host_id
        description: The id of the host. This is the primary key.
        tests:
          - unique
          - not_null
      - name: host_name
        description: The name of the host. Anonymous if not provided
        tests:
          - not_null
      - name: is_superhost
        description: Defines whether a host is a superhost, depending their performance.
        tests:
          - not_null
          - accepted_values: 
              values: [true, false]

  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        description: Primary key for the listing.
        tests:
          - unique
          - not_null
      - name: room_type
        description: Type of the apartment / room.
        tests:
          - accepted_values:
              values: ['Entire home/apt',
                'Private room',
                'Shared room',
                'Hotel room']
      - name: host_id
        description: The hosts's id. References the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id
      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value

  - name: dim_listings_with_hosts
    description: Unified dimension combining Airbnb listings with their respective hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

  - name: fct_reviews
    description: Incremental fact table containing listing reviews
    tests:
      - reviews_null_comment_and_sentiment_percentage:
          percent: 5
          config:
            severity: warn
    columns:
      - name: review_id
        tests:
          - unique
          - not_null

  - name: mart_fullmoon_reviews
    description: Reviews flagged as either 1 day after full moon or not
    columns:
      - name: is_full_moon
        tests:
          - not_null
          - accepted_values: 
              values: [true, false]

  - name: review_sentiment_by_month
    description: Monthly sentiment distribution
    columns:
      - name: review_month
        tests:
          - not_null
      - name: review_sentiment
        tests:
          - not_null
          - accepted_values:
              values: ['negative', 'neutral', 'positive']
      - name: reviews_count
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - positive_value

  - name: price_sentiment_correlation
    description: Price statistics by sentiment in reviews one day after full moon
    columns:
      - name: avg_price
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: price_stddev
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
      - name: median_price
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
  
  - name: new_listings_time_series
    description: Monthly count of new listings
    columns:
      - name: listing_month
        tests:
          - not_null
          - unique
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
          - listing_time_series_all_months
      - name: new_listings
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0

  - name: dim_listings_with_hosts_distribution_analysis
    description: Categorizes listings by price range, minimum nights required, and stay duration type to support cross-sectional analysis of pricing vs. rental policies
    columns:
      - name: minimum_nights_category
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
      - name: stay_duration_type
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
      - name: price_category
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar